### ISSUE TITLE
ical-generator 1.0

### ISSUE THREAD

**Issue by sebbo2002** [sebbo2002/ical-generator#72]
This issue should represent the current state of the ical-generator 3.0 rebuilding…

#### General
- [x] make all the tests green again 🙈

#### Deployment & Distribution
- [x] ES6 & browserify
- [x] node's require, basic inline, ES6 Module ES5 Module, AMD
- [x] browser support
- [x] browser tests
- [x] new CI Build Pipeline
    - [x] install
    - [x] build (build browser, build amd, checks)
    - [x] test (node 4+)
    - [x] publish (npm, plato, github, github-release)
        - [x] github
        - [x] plato/develop
        - [x] npm/develop
        - [x] npm/master
        - [x] github-release/master

#### Implementation
- [x] current basics
- [x] moment.js everywhere
    - [x] should fix #38 
    - [x] should fix #49 
    - [x] should fix #52 
- [x] Errors instead of thrown strings

#### Features
- [x] attendee roles (#65)
- [x] rsvp (#58)
- [x] alarm & category support (#22)
- [x] CREATED and LAST-MODIFIED (#75)
- [x] TypeScript Support (#71)

#### Tests
- [x] isolated tests (#54)
    - [x] index
    - [x] calendar
    - [x] event
    - [x] alarm
    - [x] attendee
- [x] go throught coverage report

#### Last steps
- [x] Double check throws
- [x] Double check error urls
- [x] Double check examples
- [x] Double check documentation
- [x] [RunKit?](https://npm.runkit.com/)
- [x] [Documentation: webpack fs resolve](https://github.com/sebbo2002/ical-generator/issues/64)

**Comment by antoinerousseau** [comment]
looking good! can't wait :)

**Comment by sebbo2002** [comment]
I think we're done… 🙌🏼
